source 'https://rubygems.org'

gem 'bundler'
gem 'rails', '4.0.2'
gem 'pg',    '~> 0.17.1'

gem 'sass-rails', '~> 4.0.1'
gem 'bootstrap-sass', '~> 3.0.2.0'
gem 'uglifier',   '>= 1.3.0'
gem 'jquery-rails', '~> 3.0.1'
gem 'foreigner', '~> 1.6.1'
gem 'haml', '~> 4.0.5'

group :development do
  gem 'better_errors', '~> 2.9.1'
end

group :test, :development do
  gem 'rspec-rails', '~> 2.14.1'
  gem 'pry', '~> 0.9.12'
  gem 'pry-rails', '~> 0.3.2'
  gem 'factory_girl_rails', '~> 4.3.0'
  gem 'shoulda-matchers', '~> 2.5.0'
end

group :test do
  gem 'capybara', '~> 2.2.1'
  gem 'capybara-webkit', '~> 1.0.0'
  gem 'database_cleaner', '~> 1.2.0'
  gem 'launchy', '~> 2.4.2'
end
